"""empty message

Revision ID: f0c94f99a36b
Revises: 
Create Date: 2021-07-01 19:13:39.006166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c94f99a36b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('id_pet', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pet'], ['Pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Toys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('id_pet', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pet'], ['Pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Toys')
    op.drop_table('Owners')
    op.drop_table('Pets')
    # ### end Alembic commands ###
